//go:build ignore

package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

var letters = []string{"A", "B", "C", "D", "E", "F", "G", "H"}

func main() {
	var out strings.Builder
	out.WriteString("// Code generated by internal/bindgen; DO NOT EDIT.\n\npackage causal\n\nimport (\n\t\"context\"\n\n\t\"github.com/google/cel-go/common/types/ref\"\n)\n\n")
	for arity := 0; arity <= 8; arity++ {
		writeWrappers(&out, arity)
	}
	for arity := 0; arity <= 8; arity++ {
		writeBinder(&out, arity)
	}
	source, err := format.Source([]byte(out.String()))
	if err != nil {
		panic(err)
	}
	path := filepath.Join("bind_typed.go")
	if err := os.WriteFile(path, source, 0o644); err != nil {
		panic(err)
	}
}

func writeWrappers(out *strings.Builder, arity int) {
	types := typeParameters(arity)
	args := arguments(arity)
	ctxArgs := prefixedArguments("ctx", arity)
	params := parameterTypes(arity)
	article := "a"
	if arity == 8 {
		article = "an"
	}
	fmt.Fprintf(out, "// BindFunc%d binds %s %s-argument function without reflective invocation.\n", arity, article, numberWord(arity))
	fmt.Fprintf(out, "func BindFunc%d%s(name string, function func(%s) R) Binding {\n", arity, types, params)
	fmt.Fprintf(out, "return bindTyped%d(name, function, func(_ context.Context%s) (R, error) { return function(%s), nil })\n}\n\n", arity, typedParameters(arity), args)
	fmt.Fprintf(out, "// BindFunc%dErr binds %s %s-argument function that returns an error.\n", arity, article, numberWord(arity))
	fmt.Fprintf(out, "func BindFunc%dErr%s(name string, function func(%s) (R, error)) Binding {\n", arity, types, params)
	fmt.Fprintf(out, "return bindTyped%d(name, function, func(_ context.Context%s) (R, error) { return function(%s) })\n}\n\n", arity, typedParameters(arity), args)
	fmt.Fprintf(out, "// BindContextFunc%d binds %s %s-argument context function.\n", arity, article, numberWord(arity))
	fmt.Fprintf(out, "func BindContextFunc%d%s(name string, function func(context.Context%s) R) Binding {\n", arity, types, prefixedTypes(arity))
	fmt.Fprintf(out, "return bindTyped%d(name, function, func(ctx context.Context%s) (R, error) { return function(%s), nil })\n}\n\n", arity, typedParameters(arity), ctxArgs)
	fmt.Fprintf(out, "// BindContextFunc%dErr binds %s %s-argument context function that returns an error.\n", arity, article, numberWord(arity))
	fmt.Fprintf(out, "func BindContextFunc%dErr%s(name string, function func(context.Context%s) (R, error)) Binding {\n", arity, types, prefixedTypes(arity))
	fmt.Fprintf(out, "return bindTyped%d(name, function, function)\n}\n\n", arity)
}

func writeBinder(out *strings.Builder, arity int) {
	fmt.Fprintf(out, "func bindTyped%d%s(name string, implementation any, invoke func(context.Context%s) (R, error)) Binding {\n", arity, typeParameters(arity), prefixedTypes(arity))
	fmt.Fprintf(out, "return newTypedBinding(name, implementation, &boundFunction{typedArity: %d, call%d: func(ctx context.Context%s) ref.Val {\n", arity, arity, valueParameters(arity))
	for i := 0; i < arity; i++ {
		fmt.Fprintf(out, "%s, err := typedArgument[%s](v%d)\nif err != nil { return argumentTypeError(name, %d) }\n", strings.ToLower(letters[i]), letters[i], i, i)
	}
	fmt.Fprintf(out, "result, err := invoke(ctx%s)\nreturn typedResult(result, err)\n}})\n}\n\n", prefixedArguments("", arity))
}

func typeParameters(arity int) string {
	items := append([]string(nil), letters[:arity]...)
	items = append(items, "R")
	return "[" + strings.Join(items, ", ") + " any]"
}

func parameterTypes(arity int) string { return strings.Join(letters[:arity], ", ") }
func prefixedTypes(arity int) string {
	if arity == 0 {
		return ""
	}
	return ", " + parameterTypes(arity)
}
func typedParameters(arity int) string {
	if arity == 0 {
		return ""
	}
	parts := make([]string, arity)
	for i := range parts {
		parts[i] = fmt.Sprintf(", %s %s", strings.ToLower(letters[i]), letters[i])
	}
	return strings.Join(parts, "")
}
func arguments(arity int) string {
	parts := make([]string, arity)
	for i := range parts {
		parts[i] = strings.ToLower(letters[i])
	}
	return strings.Join(parts, ", ")
}
func prefixedArguments(first string, arity int) string {
	args := arguments(arity)
	if first == "" {
		if args == "" {
			return ""
		}
		return ", " + args
	}
	if args == "" {
		return first
	}
	return first + ", " + args
}
func valueParameters(arity int) string {
	if arity == 0 {
		return ""
	}
	parts := make([]string, arity)
	for i := range parts {
		parts[i] = fmt.Sprintf("v%d", i)
	}
	return ", " + strings.Join(parts, ", ") + " ref.Val"
}
func numberWord(arity int) string {
	return []string{"zero", "one", "two", "three", "four", "five", "six", "seven", "eight"}[arity]
}
