// Code generated by internal/bindgen; DO NOT EDIT.

package causal

import (
	"context"

	"github.com/google/cel-go/common/types/ref"
)

// BindFunc0 binds a zero-argument function without reflective invocation.
func BindFunc0[R any](name string, function func() R) Binding {
	return bindTyped0(name, function, func(_ context.Context) (R, error) { return function(), nil })
}

// BindFunc0Err binds a zero-argument function that returns an error.
func BindFunc0Err[R any](name string, function func() (R, error)) Binding {
	return bindTyped0(name, function, func(_ context.Context) (R, error) { return function() })
}

// BindContextFunc0 binds a zero-argument context function.
func BindContextFunc0[R any](name string, function func(context.Context) R) Binding {
	return bindTyped0(name, function, func(ctx context.Context) (R, error) { return function(ctx), nil })
}

// BindContextFunc0Err binds a zero-argument context function that returns an error.
func BindContextFunc0Err[R any](name string, function func(context.Context) (R, error)) Binding {
	return bindTyped0(name, function, function)
}

// BindFunc1 binds a one-argument function without reflective invocation.
func BindFunc1[A, R any](name string, function func(A) R) Binding {
	return bindTyped1(name, function, func(_ context.Context, a A) (R, error) { return function(a), nil })
}

// BindFunc1Err binds a one-argument function that returns an error.
func BindFunc1Err[A, R any](name string, function func(A) (R, error)) Binding {
	return bindTyped1(name, function, func(_ context.Context, a A) (R, error) { return function(a) })
}

// BindContextFunc1 binds a one-argument context function.
func BindContextFunc1[A, R any](name string, function func(context.Context, A) R) Binding {
	return bindTyped1(name, function, func(ctx context.Context, a A) (R, error) { return function(ctx, a), nil })
}

// BindContextFunc1Err binds a one-argument context function that returns an error.
func BindContextFunc1Err[A, R any](name string, function func(context.Context, A) (R, error)) Binding {
	return bindTyped1(name, function, function)
}

// BindFunc2 binds a two-argument function without reflective invocation.
func BindFunc2[A, B, R any](name string, function func(A, B) R) Binding {
	return bindTyped2(name, function, func(_ context.Context, a A, b B) (R, error) { return function(a, b), nil })
}

// BindFunc2Err binds a two-argument function that returns an error.
func BindFunc2Err[A, B, R any](name string, function func(A, B) (R, error)) Binding {
	return bindTyped2(name, function, func(_ context.Context, a A, b B) (R, error) { return function(a, b) })
}

// BindContextFunc2 binds a two-argument context function.
func BindContextFunc2[A, B, R any](name string, function func(context.Context, A, B) R) Binding {
	return bindTyped2(name, function, func(ctx context.Context, a A, b B) (R, error) { return function(ctx, a, b), nil })
}

// BindContextFunc2Err binds a two-argument context function that returns an error.
func BindContextFunc2Err[A, B, R any](name string, function func(context.Context, A, B) (R, error)) Binding {
	return bindTyped2(name, function, function)
}

// BindFunc3 binds a three-argument function without reflective invocation.
func BindFunc3[A, B, C, R any](name string, function func(A, B, C) R) Binding {
	return bindTyped3(name, function, func(_ context.Context, a A, b B, c C) (R, error) { return function(a, b, c), nil })
}

// BindFunc3Err binds a three-argument function that returns an error.
func BindFunc3Err[A, B, C, R any](name string, function func(A, B, C) (R, error)) Binding {
	return bindTyped3(name, function, func(_ context.Context, a A, b B, c C) (R, error) { return function(a, b, c) })
}

// BindContextFunc3 binds a three-argument context function.
func BindContextFunc3[A, B, C, R any](name string, function func(context.Context, A, B, C) R) Binding {
	return bindTyped3(name, function, func(ctx context.Context, a A, b B, c C) (R, error) { return function(ctx, a, b, c), nil })
}

// BindContextFunc3Err binds a three-argument context function that returns an error.
func BindContextFunc3Err[A, B, C, R any](name string, function func(context.Context, A, B, C) (R, error)) Binding {
	return bindTyped3(name, function, function)
}

// BindFunc4 binds a four-argument function without reflective invocation.
func BindFunc4[A, B, C, D, R any](name string, function func(A, B, C, D) R) Binding {
	return bindTyped4(name, function, func(_ context.Context, a A, b B, c C, d D) (R, error) { return function(a, b, c, d), nil })
}

// BindFunc4Err binds a four-argument function that returns an error.
func BindFunc4Err[A, B, C, D, R any](name string, function func(A, B, C, D) (R, error)) Binding {
	return bindTyped4(name, function, func(_ context.Context, a A, b B, c C, d D) (R, error) { return function(a, b, c, d) })
}

// BindContextFunc4 binds a four-argument context function.
func BindContextFunc4[A, B, C, D, R any](name string, function func(context.Context, A, B, C, D) R) Binding {
	return bindTyped4(name, function, func(ctx context.Context, a A, b B, c C, d D) (R, error) { return function(ctx, a, b, c, d), nil })
}

// BindContextFunc4Err binds a four-argument context function that returns an error.
func BindContextFunc4Err[A, B, C, D, R any](name string, function func(context.Context, A, B, C, D) (R, error)) Binding {
	return bindTyped4(name, function, function)
}

// BindFunc5 binds a five-argument function without reflective invocation.
func BindFunc5[A, B, C, D, E, R any](name string, function func(A, B, C, D, E) R) Binding {
	return bindTyped5(name, function, func(_ context.Context, a A, b B, c C, d D, e E) (R, error) { return function(a, b, c, d, e), nil })
}

// BindFunc5Err binds a five-argument function that returns an error.
func BindFunc5Err[A, B, C, D, E, R any](name string, function func(A, B, C, D, E) (R, error)) Binding {
	return bindTyped5(name, function, func(_ context.Context, a A, b B, c C, d D, e E) (R, error) { return function(a, b, c, d, e) })
}

// BindContextFunc5 binds a five-argument context function.
func BindContextFunc5[A, B, C, D, E, R any](name string, function func(context.Context, A, B, C, D, E) R) Binding {
	return bindTyped5(name, function, func(ctx context.Context, a A, b B, c C, d D, e E) (R, error) {
		return function(ctx, a, b, c, d, e), nil
	})
}

// BindContextFunc5Err binds a five-argument context function that returns an error.
func BindContextFunc5Err[A, B, C, D, E, R any](name string, function func(context.Context, A, B, C, D, E) (R, error)) Binding {
	return bindTyped5(name, function, function)
}

// BindFunc6 binds a six-argument function without reflective invocation.
func BindFunc6[A, B, C, D, E, F, R any](name string, function func(A, B, C, D, E, F) R) Binding {
	return bindTyped6(name, function, func(_ context.Context, a A, b B, c C, d D, e E, f F) (R, error) {
		return function(a, b, c, d, e, f), nil
	})
}

// BindFunc6Err binds a six-argument function that returns an error.
func BindFunc6Err[A, B, C, D, E, F, R any](name string, function func(A, B, C, D, E, F) (R, error)) Binding {
	return bindTyped6(name, function, func(_ context.Context, a A, b B, c C, d D, e E, f F) (R, error) { return function(a, b, c, d, e, f) })
}

// BindContextFunc6 binds a six-argument context function.
func BindContextFunc6[A, B, C, D, E, F, R any](name string, function func(context.Context, A, B, C, D, E, F) R) Binding {
	return bindTyped6(name, function, func(ctx context.Context, a A, b B, c C, d D, e E, f F) (R, error) {
		return function(ctx, a, b, c, d, e, f), nil
	})
}

// BindContextFunc6Err binds a six-argument context function that returns an error.
func BindContextFunc6Err[A, B, C, D, E, F, R any](name string, function func(context.Context, A, B, C, D, E, F) (R, error)) Binding {
	return bindTyped6(name, function, function)
}

// BindFunc7 binds a seven-argument function without reflective invocation.
func BindFunc7[A, B, C, D, E, F, G, R any](name string, function func(A, B, C, D, E, F, G) R) Binding {
	return bindTyped7(name, function, func(_ context.Context, a A, b B, c C, d D, e E, f F, g G) (R, error) {
		return function(a, b, c, d, e, f, g), nil
	})
}

// BindFunc7Err binds a seven-argument function that returns an error.
func BindFunc7Err[A, B, C, D, E, F, G, R any](name string, function func(A, B, C, D, E, F, G) (R, error)) Binding {
	return bindTyped7(name, function, func(_ context.Context, a A, b B, c C, d D, e E, f F, g G) (R, error) {
		return function(a, b, c, d, e, f, g)
	})
}

// BindContextFunc7 binds a seven-argument context function.
func BindContextFunc7[A, B, C, D, E, F, G, R any](name string, function func(context.Context, A, B, C, D, E, F, G) R) Binding {
	return bindTyped7(name, function, func(ctx context.Context, a A, b B, c C, d D, e E, f F, g G) (R, error) {
		return function(ctx, a, b, c, d, e, f, g), nil
	})
}

// BindContextFunc7Err binds a seven-argument context function that returns an error.
func BindContextFunc7Err[A, B, C, D, E, F, G, R any](name string, function func(context.Context, A, B, C, D, E, F, G) (R, error)) Binding {
	return bindTyped7(name, function, function)
}

// BindFunc8 binds an eight-argument function without reflective invocation.
func BindFunc8[A, B, C, D, E, F, G, H, R any](name string, function func(A, B, C, D, E, F, G, H) R) Binding {
	return bindTyped8(name, function, func(_ context.Context, a A, b B, c C, d D, e E, f F, g G, h H) (R, error) {
		return function(a, b, c, d, e, f, g, h), nil
	})
}

// BindFunc8Err binds an eight-argument function that returns an error.
func BindFunc8Err[A, B, C, D, E, F, G, H, R any](name string, function func(A, B, C, D, E, F, G, H) (R, error)) Binding {
	return bindTyped8(name, function, func(_ context.Context, a A, b B, c C, d D, e E, f F, g G, h H) (R, error) {
		return function(a, b, c, d, e, f, g, h)
	})
}

// BindContextFunc8 binds an eight-argument context function.
func BindContextFunc8[A, B, C, D, E, F, G, H, R any](name string, function func(context.Context, A, B, C, D, E, F, G, H) R) Binding {
	return bindTyped8(name, function, func(ctx context.Context, a A, b B, c C, d D, e E, f F, g G, h H) (R, error) {
		return function(ctx, a, b, c, d, e, f, g, h), nil
	})
}

// BindContextFunc8Err binds an eight-argument context function that returns an error.
func BindContextFunc8Err[A, B, C, D, E, F, G, H, R any](name string, function func(context.Context, A, B, C, D, E, F, G, H) (R, error)) Binding {
	return bindTyped8(name, function, function)
}

func bindTyped0[R any](name string, implementation any, invoke func(context.Context) (R, error)) Binding {
	return newTypedBinding(name, implementation, &boundFunction{typedArity: 0, call0: func(ctx context.Context) ref.Val {
		result, err := invoke(ctx)
		return typedResult(result, err)
	}})
}

func bindTyped1[A, R any](name string, implementation any, invoke func(context.Context, A) (R, error)) Binding {
	return newTypedBinding(name, implementation, &boundFunction{typedArity: 1, call1: func(ctx context.Context, v0 ref.Val) ref.Val {
		a, err := typedArgument[A](v0)
		if err != nil {
			return argumentTypeError(name, 0)
		}
		result, err := invoke(ctx, a)
		return typedResult(result, err)
	}})
}

func bindTyped2[A, B, R any](name string, implementation any, invoke func(context.Context, A, B) (R, error)) Binding {
	return newTypedBinding(name, implementation, &boundFunction{typedArity: 2, call2: func(ctx context.Context, v0, v1 ref.Val) ref.Val {
		a, err := typedArgument[A](v0)
		if err != nil {
			return argumentTypeError(name, 0)
		}
		b, err := typedArgument[B](v1)
		if err != nil {
			return argumentTypeError(name, 1)
		}
		result, err := invoke(ctx, a, b)
		return typedResult(result, err)
	}})
}

func bindTyped3[A, B, C, R any](name string, implementation any, invoke func(context.Context, A, B, C) (R, error)) Binding {
	return newTypedBinding(name, implementation, &boundFunction{typedArity: 3, call3: func(ctx context.Context, v0, v1, v2 ref.Val) ref.Val {
		a, err := typedArgument[A](v0)
		if err != nil {
			return argumentTypeError(name, 0)
		}
		b, err := typedArgument[B](v1)
		if err != nil {
			return argumentTypeError(name, 1)
		}
		c, err := typedArgument[C](v2)
		if err != nil {
			return argumentTypeError(name, 2)
		}
		result, err := invoke(ctx, a, b, c)
		return typedResult(result, err)
	}})
}

func bindTyped4[A, B, C, D, R any](name string, implementation any, invoke func(context.Context, A, B, C, D) (R, error)) Binding {
	return newTypedBinding(name, implementation, &boundFunction{typedArity: 4, call4: func(ctx context.Context, v0, v1, v2, v3 ref.Val) ref.Val {
		a, err := typedArgument[A](v0)
		if err != nil {
			return argumentTypeError(name, 0)
		}
		b, err := typedArgument[B](v1)
		if err != nil {
			return argumentTypeError(name, 1)
		}
		c, err := typedArgument[C](v2)
		if err != nil {
			return argumentTypeError(name, 2)
		}
		d, err := typedArgument[D](v3)
		if err != nil {
			return argumentTypeError(name, 3)
		}
		result, err := invoke(ctx, a, b, c, d)
		return typedResult(result, err)
	}})
}

func bindTyped5[A, B, C, D, E, R any](name string, implementation any, invoke func(context.Context, A, B, C, D, E) (R, error)) Binding {
	return newTypedBinding(name, implementation, &boundFunction{typedArity: 5, call5: func(ctx context.Context, v0, v1, v2, v3, v4 ref.Val) ref.Val {
		a, err := typedArgument[A](v0)
		if err != nil {
			return argumentTypeError(name, 0)
		}
		b, err := typedArgument[B](v1)
		if err != nil {
			return argumentTypeError(name, 1)
		}
		c, err := typedArgument[C](v2)
		if err != nil {
			return argumentTypeError(name, 2)
		}
		d, err := typedArgument[D](v3)
		if err != nil {
			return argumentTypeError(name, 3)
		}
		e, err := typedArgument[E](v4)
		if err != nil {
			return argumentTypeError(name, 4)
		}
		result, err := invoke(ctx, a, b, c, d, e)
		return typedResult(result, err)
	}})
}

func bindTyped6[A, B, C, D, E, F, R any](name string, implementation any, invoke func(context.Context, A, B, C, D, E, F) (R, error)) Binding {
	return newTypedBinding(name, implementation, &boundFunction{typedArity: 6, call6: func(ctx context.Context, v0, v1, v2, v3, v4, v5 ref.Val) ref.Val {
		a, err := typedArgument[A](v0)
		if err != nil {
			return argumentTypeError(name, 0)
		}
		b, err := typedArgument[B](v1)
		if err != nil {
			return argumentTypeError(name, 1)
		}
		c, err := typedArgument[C](v2)
		if err != nil {
			return argumentTypeError(name, 2)
		}
		d, err := typedArgument[D](v3)
		if err != nil {
			return argumentTypeError(name, 3)
		}
		e, err := typedArgument[E](v4)
		if err != nil {
			return argumentTypeError(name, 4)
		}
		f, err := typedArgument[F](v5)
		if err != nil {
			return argumentTypeError(name, 5)
		}
		result, err := invoke(ctx, a, b, c, d, e, f)
		return typedResult(result, err)
	}})
}

func bindTyped7[A, B, C, D, E, F, G, R any](name string, implementation any, invoke func(context.Context, A, B, C, D, E, F, G) (R, error)) Binding {
	return newTypedBinding(name, implementation, &boundFunction{typedArity: 7, call7: func(ctx context.Context, v0, v1, v2, v3, v4, v5, v6 ref.Val) ref.Val {
		a, err := typedArgument[A](v0)
		if err != nil {
			return argumentTypeError(name, 0)
		}
		b, err := typedArgument[B](v1)
		if err != nil {
			return argumentTypeError(name, 1)
		}
		c, err := typedArgument[C](v2)
		if err != nil {
			return argumentTypeError(name, 2)
		}
		d, err := typedArgument[D](v3)
		if err != nil {
			return argumentTypeError(name, 3)
		}
		e, err := typedArgument[E](v4)
		if err != nil {
			return argumentTypeError(name, 4)
		}
		f, err := typedArgument[F](v5)
		if err != nil {
			return argumentTypeError(name, 5)
		}
		g, err := typedArgument[G](v6)
		if err != nil {
			return argumentTypeError(name, 6)
		}
		result, err := invoke(ctx, a, b, c, d, e, f, g)
		return typedResult(result, err)
	}})
}

func bindTyped8[A, B, C, D, E, F, G, H, R any](name string, implementation any, invoke func(context.Context, A, B, C, D, E, F, G, H) (R, error)) Binding {
	return newTypedBinding(name, implementation, &boundFunction{typedArity: 8, call8: func(ctx context.Context, v0, v1, v2, v3, v4, v5, v6, v7 ref.Val) ref.Val {
		a, err := typedArgument[A](v0)
		if err != nil {
			return argumentTypeError(name, 0)
		}
		b, err := typedArgument[B](v1)
		if err != nil {
			return argumentTypeError(name, 1)
		}
		c, err := typedArgument[C](v2)
		if err != nil {
			return argumentTypeError(name, 2)
		}
		d, err := typedArgument[D](v3)
		if err != nil {
			return argumentTypeError(name, 3)
		}
		e, err := typedArgument[E](v4)
		if err != nil {
			return argumentTypeError(name, 4)
		}
		f, err := typedArgument[F](v5)
		if err != nil {
			return argumentTypeError(name, 5)
		}
		g, err := typedArgument[G](v6)
		if err != nil {
			return argumentTypeError(name, 6)
		}
		h, err := typedArgument[H](v7)
		if err != nil {
			return argumentTypeError(name, 7)
		}
		result, err := invoke(ctx, a, b, c, d, e, f, g, h)
		return typedResult(result, err)
	}})
}
